/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SLEEP_H_RPCGEN
#define _SLEEP_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct child_info {
	int num_children;
	char filename[256];
};
typedef struct child_info child_info;

struct sleep_request {
	int child_id;
	int sleep_duration;
};
typedef struct sleep_request sleep_request;

struct store_request {
	int child_id;
	int number_to_store;
};
typedef struct store_request store_request;

struct add_result {
	int sum;
};
typedef struct add_result add_result;

#define SLEEP_PROG 0x31599123
#define SLEEP_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define init 1
extern  int * init_1(child_info *, CLIENT *);
extern  int * init_1_svc(child_info *, struct svc_req *);
#define sleep 2
extern  void * sleep_1(sleep_request *, CLIENT *);
extern  void * sleep_1_svc(sleep_request *, struct svc_req *);
#define store 3
extern  void * store_1(store_request *, CLIENT *);
extern  void * store_1_svc(store_request *, struct svc_req *);
#define add 4
extern  add_result * add_1(void *, CLIENT *);
extern  add_result * add_1_svc(void *, struct svc_req *);
extern int sleep_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define init 1
extern  int * init_1();
extern  int * init_1_svc();
#define sleep 2
extern  void * sleep_1();
extern  void * sleep_1_svc();
#define store 3
extern  void * store_1();
extern  void * store_1_svc();
#define add 4
extern  add_result * add_1();
extern  add_result * add_1_svc();
extern int sleep_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_child_info (XDR *, child_info*);
extern  bool_t xdr_sleep_request (XDR *, sleep_request*);
extern  bool_t xdr_store_request (XDR *, store_request*);
extern  bool_t xdr_add_result (XDR *, add_result*);

#else /* K&R C */
extern bool_t xdr_child_info ();
extern bool_t xdr_sleep_request ();
extern bool_t xdr_store_request ();
extern bool_t xdr_add_result ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SLEEP_H_RPCGEN */
