/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "sleep.h"

bool_t
xdr_child_info (XDR *xdrs, child_info *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_int (xdrs, &objp->num_children))
		 return FALSE;
	 if (!xdr_vector (xdrs, (char *)objp->filename, 256,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sleep_request (XDR *xdrs, sleep_request *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->child_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->sleep_duration))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_store_request (XDR *xdrs, store_request *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->child_id))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->number_to_store))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_add_result (XDR *xdrs, add_result *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->sum))
		 return FALSE;
	return TRUE;
}
